In [2]:
#!pip install flask
from flask import Flask

In [3]:
# import numpy as np
# from sklearn.linear_model import LinearRegression   1
# --------------------------------------------------
# # create a instance of class object(reg) in below example  2
# reg = LinearRegression()
# ------------------------------------------------------
# reg.fit(x,y)  3

# # This is just for your reference

In [4]:
# Intialization of Flask
app = Flask(__name__) # Dir structure is required ,It take cares of dir structure to render the HTML page properly
#created a instance of Flask so that we can use any functionality of Flask class

@app.route("/")# It binds the website with a specific url 
def hello():
    return "Welcome"
print(__name__)
if __name__=="__main__":
    app.run()

__main__
 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [07/May/2022 11:05:26] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2022 11:05:26] "GET /favicon.ico HTTP/1.1" 404 -


In [5]:
# Intialization of Flask
app = Flask(__name__) # Dir structure is required ,It take cares of dir structure to render the HTML page properly
#created a instance of Flask so that we can use any functionality of Flask class

@app.route("/<name>")# It binds the website with a specific url 
def hello(name):
    return "<Html><h1>Welcome "+name+" to the Deployment session"
print(__name__)
if __name__=="__main__":
    app.run(port = 7000,debug = True)

__main__
 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: on


 * Restarting with stat


SystemExit: 1

c:\users\akash\appdata\local\programs\python\python38\lib\site-packages\IPython\core\interactiveshell.py:3449: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [2]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/ingledarshan/upGrad_Darshan/main/hiring.csv")
df.head()

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [3]:
df.shape

(8, 4)

In [4]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [5]:
df.isnull().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [6]:
df.experience.fillna(0,inplace=True)

In [7]:
df.test_score.fillna(df.test_score.mean(),inplace=True)

In [8]:
df.isnull().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

In [9]:
df

experience  test_score  interview_score  salary
0          0    8.000000                9   50000
1          0    8.000000                6   45000
2       five    6.000000                7   60000
3        two   10.000000               10   65000
4      seven    9.000000                6   70000
5      three    7.000000               10   62000
6        ten    7.857143                7   72000
7     eleven    7.000000                8   80000

# Dataset is clean and we can make a ml model on top of it

In [10]:
def conv_dict(x):
    dict={
        "five":5,
        "two":2,
        "seven":7,
        "three":3,
        "ten":10,
        "eleven":11,
        0:0
    }
    return dict[x]

In [11]:
df.experience = df.experience.apply(conv_dict)

In [12]:
df

experience  test_score  interview_score  salary
0           0    8.000000                9   50000
1           0    8.000000                6   45000
2           5    6.000000                7   60000
3           2   10.000000               10   65000
4           7    9.000000                6   70000
5           3    7.000000               10   62000
6          10    7.857143                7   72000
7          11    7.000000                8   80000

In [13]:
X = df.iloc[:,:-1]
X.shape

(8, 3)

In [14]:
y=df.iloc[:,-1]

In [15]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

# I am not doing any train and test split but you should do it in real data

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
lr = LinearRegression()
lr

LinearRegression()

In [18]:
lr.fit(X,y)

LinearRegression()

In [19]:
lr.predict(X)

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [20]:
y_pred=lr.predict(X)

In [21]:
lr.predict([[2,9,9]])

array([59881.81850176])

In [1]:
lr.predict([[2,9,9]])

NameError: name 'lr' is not defined

In [22]:
lr.predict([[2,9,9]])

array([59881.81850176])

In [23]:
import pickle
pickle.dump(lr,open("lr_c32.pkl",'wb'))# will store your model in the given name

In [2]:
import pickle
lr = pickle.load(open("lr_c32.pkl",'rb'))
lr

LinearRegression()

In [3]:
lr.predict([[2,9,9]])


array([59881.81850176])